name: 'shopstream'
version: '1.0.0'
config-version: 2

profile: 'shopstream'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  shopstream:
    min_date: '2022-01-01'
    payment_methods: ['credit_card', 'paypal', 'bank_transfer', 'gift_card']

models:
  shopstream:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      core:
        +schema: core
      finance:
        +schema: finance
      marketing:
        +schema: marketing
