"""
01_conversation_memory.py - In-Memory Conversation Management
=============================================================
Module 4: Memory Systems

This module implements two conversation memory strategies:
1. Window Memory — keep the last N messages
2. Summarizing Memory — compress old messages when history gets long

Both strategies must preserve the system prompt (index 0) and always
include the most recent user message.

Run with: python module_04_memory_systems/examples/01_conversation_memory.py
No API keys needed for the demonstration.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Optional

from dotenv import load_dotenv

load_dotenv()


@dataclass
class Message:
    role: str   # system, user, assistant, tool
    content: str

    def to_dict(self) -> dict:
        return {"role": self.role, "content": self.content}


# ──────────────────────────────────────────────────────────────
# Strategy 1: Window Memory
# ──────────────────────────────────────────────────────────────

class WindowConversationMemory:
    """
    Keeps the last N messages in the context window.

    The sliding window approach:
    - System prompt always stays (position 0)
    - Oldest user/assistant pairs are dropped when window fills up
    - O(1) operation — just slice the list

    Limitation: context before the window is completely lost.
    Use SummarizingMemory when you need to remember older context.
    """

    def __init__(self, system_prompt: str, max_messages: int = 20):
        """
        Args:
            system_prompt: Agent instructions — always first, never dropped
            max_messages: Max messages to keep (excluding system prompt).
                          Should be even (pairs of user + assistant).
        """
        self.system_prompt = system_prompt
        self.max_messages = max_messages
        self._history: list[Message] = []
        self.total_messages_added = 0  # Track total, not just current

    def add_user_message(self, content: str) -> None:
        """Add a user message to the history."""
        self._history.append(Message(role="user", content=content))
        self.total_messages_added += 1
        self._trim()

    def add_assistant_message(self, content: str) -> None:
        """Add an assistant response to the history."""
        self._history.append(Message(role="assistant", content=content))
        self.total_messages_added += 1
        self._trim()

    def _trim(self) -> None:
        """Remove oldest messages to stay within max_messages."""
        while len(self._history) > self.max_messages:
            # Remove oldest message (never the system prompt — that's separate)
            self._history.pop(0)

    def get_messages(self) -> list[dict]:
        """
        Get the message list for the LLM API call.

        System prompt is always first, followed by the windowed history.
        """
        return [
            {"role": "system", "content": self.system_prompt},
            *[m.to_dict() for m in self._history],
        ]

    def clear(self) -> None:
        """Clear history (keeps system prompt)."""
        self._history.clear()

    @property
    def current_length(self) -> int:
        return len(self._history)

    def summary(self) -> str:
        return (
            f"WindowMemory: {self.current_length}/{self.max_messages} messages "
            f"({self.total_messages_added} total added, "
            f"{self.total_messages_added - self.current_length} dropped)"
        )


# ──────────────────────────────────────────────────────────────
# Strategy 2: Summarizing Memory
# ──────────────────────────────────────────────────────────────

class SummarizingConversationMemory:
    """
    Summarizes old messages when history gets too long.

    Strategy:
    - Keep a rolling summary of all messages before the window
    - Inject the summary as an initial context message
    - Keep recent messages verbatim

    This preserves the gist of older conversation while reducing tokens.
    In production, the summary is generated by a small/cheap LLM call.
    """

    def __init__(
        self,
        system_prompt: str,
        max_messages: int = 20,
        summarize_after: int = 10,
    ):
        """
        Args:
            system_prompt: Agent instructions
            max_messages: Max recent messages to keep verbatim
            summarize_after: Summarize when history exceeds this many messages
        """
        self.system_prompt = system_prompt
        self.max_messages = max_messages
        self.summarize_after = summarize_after

        self._history: list[Message] = []
        self._summary: Optional[str] = None
        self.summaries_created = 0

    def add_user_message(self, content: str) -> None:
        self._history.append(Message(role="user", content=content))
        self._maybe_summarize()

    def add_assistant_message(self, content: str) -> None:
        self._history.append(Message(role="assistant", content=content))

    def _maybe_summarize(self) -> None:
        """Check if we need to summarize and do so if needed."""
        if len(self._history) > self.summarize_after:
            self._summarize_old_messages()

    def _summarize_old_messages(self) -> None:
        """
        Compress the oldest messages into a summary.

        In production: call a cheap LLM (gpt-4o-mini, claude-haiku)
        to produce a concise summary. Here: create a mock summary.
        """
        # Keep the most recent max_messages messages verbatim
        keep = self.max_messages // 2
        to_summarize = self._history[:-keep]
        self._history = self._history[-keep:]

        # In production, call an LLM here:
        #   summary_prompt = f"Summarize this conversation: {to_summarize}"
        #   self._summary = llm.call(summary_prompt)

        # Mock summary for demonstration
        topics = set()
        for msg in to_summarize:
            content_lower = msg.content.lower()
            if "password" in content_lower or "login" in content_lower:
                topics.add("login issues")
            if "billing" in content_lower or "charge" in content_lower:
                topics.add("billing questions")
            if "export" in content_lower:
                topics.add("data export")
            if any(w in content_lower for w in ["thank", "resolved", "fixed"]):
                topics.add("issue resolved")

        existing = self._summary or ""
        new_summary = f"[Earlier in this conversation: {', '.join(topics) or 'general support chat'}]"
        self._summary = f"{existing} {new_summary}".strip()
        self.summaries_created += 1

    def get_messages(self) -> list[dict]:
        """Get messages for the LLM, including summary as context."""
        messages = [{"role": "system", "content": self.system_prompt}]

        if self._summary:
            messages.append({
                "role": "user",
                "content": f"[Conversation context: {self._summary}]"
            })
            messages.append({
                "role": "assistant",
                "content": "Understood — I have context about our earlier conversation."
            })

        messages.extend(m.to_dict() for m in self._history)
        return messages

    def summary_stats(self) -> str:
        return (
            f"SummarizingMemory: {len(self._history)} recent messages, "
            f"{self.summaries_created} summaries created, "
            f"summary: {bool(self._summary)}"
        )


# ──────────────────────────────────────────────────────────────
# Demo
# ──────────────────────────────────────────────────────────────

def demo_window_memory():
    """Show the sliding window in action."""
    print("\n" + "=" * 60)
    print("  Window Memory Demo (max_messages=6)")
    print("=" * 60)

    memory = WindowConversationMemory(
        system_prompt="You are a support agent.",
        max_messages=6,  # Small for demo
    )

    # Simulate a conversation with 8 turns
    for i in range(1, 9):
        memory.add_user_message(f"User message #{i}")
        memory.add_assistant_message(f"Agent response #{i}")
        print(f"  After turn {i}: {memory.summary()}")

    print(f"\n  Messages in context window:")
    for msg in memory.get_messages():
        role = msg["role"]
        content = msg["content"][:40]
        print(f"    [{role}]: {content}")

    print(f"\n  Note: Messages 1-4 were dropped (window overflow)")
    print(f"  System prompt is separate and always included")


def demo_summarizing_memory():
    """Show summarization kicking in."""
    print("\n" + "=" * 60)
    print("  Summarizing Memory Demo")
    print("=" * 60)

    memory = SummarizingConversationMemory(
        system_prompt="You are a support agent.",
        max_messages=10,
        summarize_after=6,  # Summarize after 6 messages
    )

    conversation = [
        ("I can't log in", "I'll help! What error do you see?"),
        ("It says invalid password", "Let's reset it. What's your email?"),
        ("alice@example.com", "Sent a reset link to alice@example.com"),
        ("Got it, but new password also fails", "Hmm, try incognito mode"),
        ("Works in incognito! What does that mean?", "Browser extension conflict. Disable them."),
        ("That fixed it! Thanks", "Great! Anything else?"),
        ("Actually I have a billing question", "Of course, what's your question?"),
        ("Was I charged twice in January?", "Let me check your billing history..."),
    ]

    for i, (user_msg, agent_msg) in enumerate(conversation, 1):
        memory.add_user_message(user_msg)
        memory.add_assistant_message(agent_msg)
        print(f"  Turn {i}: {memory.summary_stats()}")

    print(f"\n  Summary created: {memory._summary}")
    print(f"\n  Messages now in context ({len(memory._history)} recent):")
    for msg in memory._history:
        print(f"    [{msg.role}]: {msg.content[:50]}")


def demo_comparison():
    """Compare token counts between strategies."""
    print("\n" + "=" * 60)
    print("  Strategy Comparison: Token Efficiency")
    print("=" * 60)

    messages = [
        "Hello, I need help with my account",
        "Of course! What seems to be the issue?",
        "I can't log in after changing my password",
        "Let me help you reset it. What's your email?",
        "alice@example.com",
        "I've sent a reset link. Did you receive it?",
        "Yes! But now I have a different question",
        "Sure, what would you like to know?",
        "Why was I charged twice in December?",
        "That sounds like a duplicate charge. Let me investigate.",
    ]

    system = "You are a customer support agent. Be helpful and professional."

    window = WindowConversationMemory(system, max_messages=6)
    summarizing = SummarizingConversationMemory(system, max_messages=8, summarize_after=6)

    for i, msg in enumerate(messages):
        if i % 2 == 0:
            window.add_user_message(msg)
            summarizing.add_user_message(msg)
        else:
            window.add_assistant_message(msg)
            summarizing.add_assistant_message(msg)

    window_total = sum(len(m["content"]) for m in window.get_messages())
    summ_total = sum(len(m["content"]) for m in summarizing.get_messages())

    print(f"\n  After {len(messages)//2} turns:")
    print(f"\n  Window Memory:")
    print(f"    Messages sent to LLM: {len(window.get_messages())}")
    print(f"    Approx chars in context: {window_total:,}")
    print(f"    History preserved: Last {window.current_length} messages")

    print(f"\n  Summarizing Memory:")
    print(f"    Messages sent to LLM: {len(summarizing.get_messages())}")
    print(f"    Approx chars in context: {summ_total:,}")
    print(f"    Summaries created: {summarizing.summaries_created}")


if __name__ == "__main__":
    demo_window_memory()
    demo_summarizing_memory()
    demo_comparison()
