"""
01_fastapi_agent.py - FastAPI HTTP API for the Support Agent
=============================================================
Module 9: Production Deployment

Wraps the support agent in a production-ready FastAPI application:
- POST /tickets — submit a ticket for AI processing
- GET /tickets/{id} — retrieve a processed ticket
- GET /health — health check for load balancers
- GET /metrics — basic performance metrics

Key production patterns demonstrated:
1. Request/response validation with Pydantic
2. Background tasks for async processing
3. Structured JSON responses
4. Correlation IDs for distributed tracing
5. Proper HTTP status codes
6. OpenAPI documentation (auto-generated by FastAPI)

Run with: uvicorn module_09_production.examples.01_fastapi_agent:app --reload
Or:        python module_09_production/examples/01_fastapi_agent.py
"""

from __future__ import annotations

import os
import time
import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Optional

from fastapi import FastAPI, HTTPException, BackgroundTasks, Header, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, EmailStr, Field, field_validator

from dotenv import load_dotenv

load_dotenv()


# ──────────────────────────────────────────────────────────────
# Pydantic Models (Request/Response Schemas)
# ──────────────────────────────────────────────────────────────

class TicketRequest(BaseModel):
    """Incoming support ticket from the API."""
    subject: str = Field(..., min_length=5, max_length=200, description="Ticket subject")
    body: str = Field(..., min_length=10, max_length=10000, description="Ticket description")
    customer_email: str = Field(..., description="Customer's email address")
    priority: Optional[str] = Field(None, description="Optional priority hint: low/medium/high")

    @field_validator("priority")
    @classmethod
    def validate_priority(cls, v):
        if v is not None and v not in ("low", "medium", "high"):
            raise ValueError("priority must be 'low', 'medium', or 'high'")
        return v

    @field_validator("customer_email")
    @classmethod
    def validate_email(cls, v):
        if "@" not in v or "." not in v.split("@")[-1]:
            raise ValueError("Invalid email address format")
        return v.lower()

    model_config = {
        "json_schema_extra": {
            "example": {
                "subject": "Can't log in to my account",
                "body": "I forgot my password and the reset email isn't arriving.",
                "customer_email": "alice@example.com",
                "priority": "high",
            }
        }
    }


class TicketResponse(BaseModel):
    """Response after submitting a ticket."""
    ticket_id: str
    status: str
    message: str
    created_at: str


class TicketDetail(BaseModel):
    """Full ticket details including agent response."""
    ticket_id: str
    subject: str
    customer_email: str
    status: str
    category: Optional[str]
    priority: str
    agent_response: Optional[str]
    should_escalate: bool
    confidence: float
    processing_time_ms: Optional[int]
    created_at: str
    updated_at: str


class HealthResponse(BaseModel):
    """Health check response."""
    status: str
    version: str
    uptime_seconds: float
    checks: dict[str, str]


class MetricsResponse(BaseModel):
    """Performance metrics."""
    total_tickets: int
    processed_tickets: int
    pending_tickets: int
    avg_processing_time_ms: float
    escalation_rate: float


# ──────────────────────────────────────────────────────────────
# In-Memory Store (replace with PostgreSQL in production)
# ──────────────────────────────────────────────────────────────

ticket_store: dict[str, dict] = {}
metrics_store = {
    "total": 0,
    "processed": 0,
    "total_processing_ms": 0,
    "escalations": 0,
}
app_start_time = time.time()


# ──────────────────────────────────────────────────────────────
# Agent Logic (simplified for demo)
# ──────────────────────────────────────────────────────────────

def process_ticket_sync(ticket_id: str, subject: str, body: str, email: str) -> dict:
    """
    Process a support ticket using the AI agent.

    In production, this would call the full agent pipeline.
    Here we demonstrate the structure with mock logic.
    """
    start = time.time()

    # Triage
    text = f"{subject} {body}".lower()
    if any(w in text for w in ["charge", "billing", "invoice", "refund"]):
        category = "billing"
        should_escalate = True
    elif any(w in text for w in ["error", "bug", "crash"]):
        category = "technical"
        should_escalate = True
    elif any(w in text for w in ["password", "login", "access"]):
        category = "account_access"
        should_escalate = False
    else:
        category = "general"
        should_escalate = False

    # Extract name from email
    username = email.split("@")[0]
    name = username.replace(".", " ").replace("_", " ").title()

    # Generate response
    if category == "account_access":
        response = (
            f"Hi {name},\n\n"
            f"For account access issues, please try:\n"
            f"1. Visit the login page and click 'Forgot Password'\n"
            f"2. Enter your email address\n"
            f"3. Check your inbox for a reset link (valid 24 hours)\n\n"
            f"If the issue persists, please reply to this ticket."
        )
        confidence = 0.88
    elif category == "billing":
        response = (
            f"Hi {name},\n\n"
            f"Our billing team will review your account and respond within 1 business day. "
            f"For urgent billing issues, please email billing@example.com."
        )
        confidence = 0.82
    else:
        response = (
            f"Hi {name},\n\n"
            f"Thank you for contacting us. Our team will investigate and respond within 24 hours."
        )
        confidence = 0.70

    processing_time = int((time.time() - start) * 1000)

    return {
        "category": category,
        "should_escalate": should_escalate,
        "agent_response": response,
        "confidence": confidence,
        "processing_time_ms": processing_time,
    }


# ──────────────────────────────────────────────────────────────
# Background Task
# ──────────────────────────────────────────────────────────────

async def process_ticket_background(ticket_id: str):
    """
    Process a ticket asynchronously.

    FastAPI background tasks run after the response is sent to the client,
    so the client gets an immediate acknowledgment while processing happens.
    """
    ticket = ticket_store.get(ticket_id)
    if not ticket:
        return

    try:
        result = process_ticket_sync(
            ticket_id,
            ticket["subject"],
            ticket["body"],
            ticket["customer_email"],
        )

        ticket.update({
            "status": "resolved" if not result["should_escalate"] else "escalated",
            "category": result["category"],
            "agent_response": result["agent_response"],
            "should_escalate": result["should_escalate"],
            "confidence": result["confidence"],
            "processing_time_ms": result["processing_time_ms"],
            "updated_at": datetime.now(timezone.utc).isoformat(),
        })

        # Update metrics
        metrics_store["processed"] += 1
        metrics_store["total_processing_ms"] += result["processing_time_ms"]
        if result["should_escalate"]:
            metrics_store["escalations"] += 1

    except Exception as e:
        ticket.update({
            "status": "error",
            "error_message": str(e),
            "updated_at": datetime.now(timezone.utc).isoformat(),
        })


# ──────────────────────────────────────────────────────────────
# FastAPI App
# ──────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application startup and shutdown."""
    print("  Support Agent API starting up...")
    yield
    print("  Support Agent API shutting down...")


app = FastAPI(
    title="AI Support Agent API",
    description="Customer support ticket processing with AI agents",
    version="1.0.0",
    lifespan=lifespan,
)

# CORS for web frontends
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────────
# Routes
# ──────────────────────────────────────────────────────────────

@app.post("/tickets", response_model=TicketResponse, status_code=202)
async def submit_ticket(
    request: TicketRequest,
    background_tasks: BackgroundTasks,
    x_correlation_id: Optional[str] = Header(None),
):
    """
    Submit a support ticket for AI processing.

    Returns immediately with a ticket ID. Processing happens in background.
    Poll GET /tickets/{id} for the result.

    HTTP 202 Accepted means: "we received it, processing in progress."
    """
    ticket_id = f"TKT-{str(uuid.uuid4())[:8].upper()}"
    now = datetime.now(timezone.utc).isoformat()

    # Store ticket with initial status
    ticket_store[ticket_id] = {
        "ticket_id": ticket_id,
        "subject": request.subject,
        "body": request.body,
        "customer_email": request.customer_email,
        "priority": request.priority or "medium",
        "status": "processing",
        "category": None,
        "agent_response": None,
        "should_escalate": False,
        "confidence": 0.0,
        "processing_time_ms": None,
        "created_at": now,
        "updated_at": now,
        "correlation_id": x_correlation_id,
    }

    metrics_store["total"] += 1

    # Queue background processing
    background_tasks.add_task(process_ticket_background, ticket_id)

    return TicketResponse(
        ticket_id=ticket_id,
        status="processing",
        message="Ticket received. Processing in background.",
        created_at=now,
    )


@app.get("/tickets/{ticket_id}", response_model=TicketDetail)
async def get_ticket(ticket_id: str):
    """
    Retrieve a ticket by ID.

    Returns the current status and agent response if processing is complete.
    """
    ticket = ticket_store.get(ticket_id)
    if not ticket:
        raise HTTPException(
            status_code=404,
            detail=f"Ticket {ticket_id} not found",
        )

    return TicketDetail(
        ticket_id=ticket["ticket_id"],
        subject=ticket["subject"],
        customer_email=ticket["customer_email"],
        status=ticket["status"],
        category=ticket.get("category"),
        priority=ticket["priority"],
        agent_response=ticket.get("agent_response"),
        should_escalate=ticket.get("should_escalate", False),
        confidence=ticket.get("confidence", 0.0),
        processing_time_ms=ticket.get("processing_time_ms"),
        created_at=ticket["created_at"],
        updated_at=ticket["updated_at"],
    )


@app.get("/tickets", response_model=list[TicketDetail])
async def list_tickets(
    status: Optional[str] = None,
    limit: int = 20,
):
    """
    List tickets with optional status filter.
    """
    tickets = list(ticket_store.values())

    if status:
        tickets = [t for t in tickets if t.get("status") == status]

    tickets.sort(key=lambda t: t["created_at"], reverse=True)
    tickets = tickets[:limit]

    return [
        TicketDetail(
            ticket_id=t["ticket_id"],
            subject=t["subject"],
            customer_email=t["customer_email"],
            status=t["status"],
            category=t.get("category"),
            priority=t["priority"],
            agent_response=t.get("agent_response"),
            should_escalate=t.get("should_escalate", False),
            confidence=t.get("confidence", 0.0),
            processing_time_ms=t.get("processing_time_ms"),
            created_at=t["created_at"],
            updated_at=t["updated_at"],
        )
        for t in tickets
    ]


@app.get("/health", response_model=HealthResponse)
async def health_check():
    """
    Health check endpoint for load balancers and monitoring.

    Returns 200 when healthy, 503 when degraded.
    """
    checks = {"api": "healthy"}

    # Check optional services
    try:
        import redis
        r = redis.Redis.from_url(os.environ.get("REDIS_URL", "redis://localhost:6379"), socket_timeout=1)
        r.ping()
        checks["redis"] = "healthy"
    except Exception:
        checks["redis"] = "unavailable"

    overall = "healthy" if all(v == "healthy" for v in checks.values()) else "degraded"

    return HealthResponse(
        status=overall,
        version="1.0.0",
        uptime_seconds=round(time.time() - app_start_time, 1),
        checks=checks,
    )


@app.get("/metrics", response_model=MetricsResponse)
async def get_metrics():
    """
    Basic performance metrics.

    In production, use Prometheus + Grafana for proper metrics.
    """
    total = metrics_store["total"]
    processed = metrics_store["processed"]
    avg_ms = (
        metrics_store["total_processing_ms"] / processed
        if processed > 0
        else 0.0
    )
    escalation_rate = (
        metrics_store["escalations"] / processed
        if processed > 0
        else 0.0
    )

    return MetricsResponse(
        total_tickets=total,
        processed_tickets=processed,
        pending_tickets=total - processed,
        avg_processing_time_ms=round(avg_ms, 1),
        escalation_rate=round(escalation_rate, 3),
    )


# ──────────────────────────────────────────────────────────────
# Run directly (not with uvicorn)
# ──────────────────────────────────────────────────────────────

def demo_direct():
    """Demonstrate the API logic without starting an HTTP server."""
    import asyncio

    print("\n" + "=" * 60)
    print("  FastAPI Support Agent — Direct Demo")
    print("=" * 60)
    print("  (For HTTP server: uvicorn 01_fastapi_agent:app --reload)")
    print()

    async def run():
        from fastapi.testclient import TestClient

        try:
            client = TestClient(app)

            # Submit a ticket
            print("  POST /tickets")
            response = client.post("/tickets", json={
                "subject": "Can't log in after password reset",
                "body": "I clicked forgot password but the email never came through.",
                "customer_email": "alice@example.com",
            })
            print(f"    Status: {response.status_code}")
            data = response.json()
            ticket_id = data["ticket_id"]
            print(f"    Ticket ID: {ticket_id}")

            # Small delay for background processing
            await asyncio.sleep(0.1)

            # Retrieve the ticket
            print(f"\n  GET /tickets/{ticket_id}")
            response = client.get(f"/tickets/{ticket_id}")
            data = response.json()
            print(f"    Status: {data['status']}")
            print(f"    Category: {data['category']}")
            print(f"    Should escalate: {data['should_escalate']}")
            if data.get("agent_response"):
                print(f"    Response: {data['agent_response'][:80]}...")

            # Health check
            print("\n  GET /health")
            response = client.get("/health")
            data = response.json()
            print(f"    Status: {data['status']}")
            print(f"    Uptime: {data['uptime_seconds']}s")

            # Metrics
            print("\n  GET /metrics")
            response = client.get("/metrics")
            data = response.json()
            print(f"    Total tickets: {data['total_tickets']}")
            print(f"    Avg processing: {data['avg_processing_time_ms']}ms")

        except ImportError:
            print("  httpx not installed — install with: pip install httpx")
            print("  Showing ticket processing logic directly:\n")

            # Direct processing demo
            result = process_ticket_sync(
                "TKT-DEMO",
                "Can't log in",
                "I forgot my password",
                "alice@example.com",
            )
            print(f"    Category: {result['category']}")
            print(f"    Escalate: {result['should_escalate']}")
            print(f"    Confidence: {result['confidence']:.0%}")
            print(f"    Response: {result['agent_response'][:100]}...")

    asyncio.run(run())


if __name__ == "__main__":
    import sys
    if "--serve" in sys.argv:
        import uvicorn
        uvicorn.run("01_fastapi_agent:app", host="0.0.0.0", port=8080, reload=True)
    else:
        demo_direct()
